# Dependencies

markdown:         Kramdown

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SiriuzPlay
tagline:          "Yichen Zhou's Homepage"
description:      ""
url:              http://www.siriuzplay.com
baseurl:          /

author:
  name:           'Yichen Zhou'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/siriuz42/siriuz42.github.io
